# Nome do executável
TARGET = gerenciador

# Diretórios
SRC_DIR = src
INCLUDE_DIR = include

# Compilador e flags
CC = g++
CFLAGS = -Wall -I$(INCLUDE_DIR)

# Obter arquivos .cpp e .o
SRCS = $(wildcard $(SRC_DIR)/*.cpp)
OBJS = $(SRCS:.cpp=.o)

# Regra principal
$(TARGET): $(OBJS)
	$(CC) -o $@ $^

# Regra para compilar arquivos .cpp em .o
%.o: %.cpp
	$(CC) $(CFLAGS) -c -o $@ $<

# Limpeza
clean:
	rm -f $(OBJS) $(TARGET)

# Limpeza de arquivos .o na pasta src
clean-objects:
	rm -f $(SRC_DIR)/*.o
